name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: JhalakGupta/Actions@v5.1.2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
