name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fountainhead/action-wait-for-check@v1.0.0
      with:
       ref: master
       check-name: test
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       wait-interval: 30
    - uses: JhalakGupta/Actions@v5.1.2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
